// Generated by https://quicktype.io

export interface IShow {
  id: number;
  url: string;
  name: string;
  type: Type;
  language: Language;
  genres: string[];
  status: Status;
  runtime: number | null;
  averageRuntime: number | null;
  premiered: null | string;
  ended: null | string;
  officialSite: null | string;
  schedule: Schedule;
  rating: Rating;
  weight: number;
  network: Network | null;
  webChannel: Network | null;
  dvdCountry: null;
  externals: Externals;
  image: Image;
  summary: string;
  updated: number;
  _links: Links;
}

export interface Links {
  self: Nextepisode;
  previousepisode?: Nextepisode;
  nextepisode?: Nextepisode;
}

export interface Nextepisode {
  href: string;
}

export interface Externals {
  tvrage: number;
  thetvdb: number | null;
  imdb: null | string;
}

export interface Image {
  medium: string;
  original: string;
}

export enum Language {
  English = "English",
  Japanese = "Japanese",
}

export interface Network {
  id: number;
  name: string;
  country: Country | null;
  officialSite: null | string;
}

export interface Country {
  name: Name;
  code: Code;
  timezone: Timezone;
}

export enum Code {
  CA = "CA",
  Fr = "FR",
  GB = "GB",
  Jp = "JP",
  Us = "US",
}

export enum Name {
  Canada = "Canada",
  France = "France",
  Japan = "Japan",
  UnitedKingdom = "United Kingdom",
  UnitedStates = "United States",
}

export enum Timezone {
  AmericaHalifax = "America/Halifax",
  AmericaNewYork = "America/New_York",
  AsiaTokyo = "Asia/Tokyo",
  EuropeLondon = "Europe/London",
  EuropeParis = "Europe/Paris",
}

export interface Rating {
  average: number | null;
}

export interface Schedule {
  time: string;
  days: Day[];
}

export enum Day {
  Friday = "Friday",
  Monday = "Monday",
  Saturday = "Saturday",
  Sunday = "Sunday",
  Thursday = "Thursday",
  Tuesday = "Tuesday",
  Wednesday = "Wednesday",
}

export enum Status {
  Ended = "Ended",
  Running = "Running",
  ToBeDetermined = "To Be Determined",
}

export enum Type {
  Animation = "Animation",
  Documentary = "Documentary",
  News = "News",
  PanelShow = "Panel Show",
  Reality = "Reality",
  Scripted = "Scripted",
  Sports = "Sports",
  TalkShow = "Talk Show",
  Variety = "Variety",
}
